-- One row per pitch (grain: pitch_key). Curated projection of the 120-column Statcast feed,
-- typed and renamed for the models. xwOBA gets a readable name. Runner columns stay as MLBAM
-- ids (null = base empty); silver derives the base-out state from them.
select
    pitch_key,
    game_pk,
    game_date,
    game_type,
    game_year                               as season,
    home_team,
    away_team,
    batter                                  as batter_id,
    pitcher                                 as pitcher_id,
    fielder_2                               as catcher_id,
    stand                                   as batter_side,
    p_throws                                as pitcher_hand,
    at_bat_number,
    pitch_number,
    inning,
    inning_topbot,
    balls,
    strikes,
    outs_when_up,
    on_1b                                   as runner_1b_id,
    on_2b                                   as runner_2b_id,
    on_3b                                   as runner_3b_id,
    events,
    description,
    type                                    as pitch_result,   -- S / B / X
    pitch_type,
    pitch_name,
    bb_type,
    release_speed,
    release_spin_rate,
    pfx_x,
    pfx_z,
    plate_x,
    plate_z,
    zone,
    sz_top,
    sz_bot,
    launch_speed,
    launch_angle,
    estimated_woba_using_speedangle         as xwoba,
    woba_value,
    woba_denom,
    babip_value,
    delta_run_exp,
    bat_score,
    fld_score,
    home_score,
    away_score,
    post_home_score,
    post_away_score
from {{ source('bronze', 'statcast') }}
-- Scope to the frozen analysis seasons (the live current season is handled by a separate track).
where game_year in ({{ var('analysis_seasons') | join(', ') }})
